name: Production Workflow

type: workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_ios_production:
    name: Build iOS production
    type: build
    params:
      platform: ios
      profile: production

  build_android_production:
    name: Build Android production
    needs: [build_ios_production]
    type: build
    params:
      platform: android
      profile: production

  submit_ios_production:
    name: Submit iOS to App Store
    needs: [build_ios_production]
    type: submit
    params:
      platform: ios
      profile: production

  submit_android_production:
    name: Submit Android to Google Play
    needs: [build_android_production]
    type: submit
    params:
      platform: android
      profile: production

  update_production:
    name: OTA update production
    needs: [build_ios_production, build_android_production]
    type: update
    params:
      channel: production
      message: "Production update"
